version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Frontend.Dockerfile
    ports:
      - "80:80"
    environment:
      - API_URL=http://backend:5000

  backend:
    build:
      context: .
      dockerfile: backend/Backend.Dockerfile
    ports:
      - "5000:80"
    env_file:
      - .env
