version: '3.5'

services:
  backend:
    build:
      context: .
      dockerfile: WebApp.arm64.Dockerfile
    container_name: chatgpt
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env